### ISSUE TITLE
page should be response

### ISSUE THREAD

**Issue by apotonick** [ordinaryzelig/capybara_minitest_spec#15]
Sorry for not opening a PR, I'm lame.

In your docs, it says 

```ruby
page.must_have_content('Title')
```

and I am assuming this is a controller test in MiniTest::Spec, in Rails. However, I only got it working with the following massive "rewrite".

```ruby
response.must_have_content('Title')
```

The `page` variable wasn't defined in my controller test, but maybe that's `minitest-spec-rails` fault? Thanks for your work.

**Comment by ordinaryzelig** [comment]
These are for integration tests, not so much controller tests. I'm actually surprised `response.must_have_content('Title')` worked for you. `page` is a method Capybara provides when you include the Capybara DSL in an integration test. Not sure what the behavior is when you include it in controller tests. I've never used `minitest-spec-rails` before, but I can't imagine it has anything to do with `page` not being defined since it's Capybara's responsibility to do it.

**Comment by apotonick** [comment]
BTW, I needed to use `response.body`, which is a string and works as you include the matchers. Thanks. I might come back with some extension code.

**Comment by ordinaryzelig** [comment]
Closing to keep issues clean.
